-- 创建数据库
CREATE DATABASE IF NOT EXISTS boss;
-- 指定数据库
USE boss;
-- user
CREATE TABLE IF NOT EXISTS `fed`(
    `id` INT UNSIGNED AUTO_INCREMENT KEY,
    `jobName` LONGTEXT NOT NULL COMMENT '职位名称',
    `salary` VARCHAR(20) NOT NULL COMMENT '薪资范围',
    `companyName` VARCHAR(50) NOT NULL COMMENT '公司名称',
    `companyInfo` VARCHAR(50) NOT NULL COMMENT '公司信息',
    `time` VARCHAR(20) NOT NULL COMMENT '发布日期',
    `description` LONGTEXT NOT NULL COMMENT '职位描述'
)ENGINE=INNODB CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `php`(
    `id` INT UNSIGNED AUTO_INCREMENT KEY,
    `jobName` LONGTEXT NOT NULL COMMENT '职位名称',
    `salary` VARCHAR(20) NOT NULL COMMENT '薪资范围',
    `companyName` VARCHAR(50) NOT NULL COMMENT '公司名称',
    `companyInfo` VARCHAR(50) NOT NULL COMMENT '公司信息',
    `time` VARCHAR(20) NOT NULL COMMENT '发布日期',
    `description` LONGTEXT NOT NULL COMMENT '职位描述'
)ENGINE=INNODB CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `node`(
    `id` INT UNSIGNED AUTO_INCREMENT KEY,
    `jobName` LONGTEXT NOT NULL COMMENT '职位名称',
    `salary` VARCHAR(20) NOT NULL COMMENT '薪资范围',
    `companyName` VARCHAR(50) NOT NULL COMMENT '公司名称',
    `companyInfo` VARCHAR(50) NOT NULL COMMENT '公司信息',
    `time` VARCHAR(20) NOT NULL COMMENT '发布日期',
    `description` LONGTEXT NOT NULL COMMENT '职位描述'
)ENGINE=INNODB CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `python`(
    `id` INT UNSIGNED AUTO_INCREMENT KEY,
    `jobName` LONGTEXT NOT NULL COMMENT '职位名称',
    `salary` VARCHAR(20) NOT NULL COMMENT '薪资范围',
    `companyName` VARCHAR(50) NOT NULL COMMENT '公司名称',
    `companyInfo` VARCHAR(50) NOT NULL COMMENT '公司信息',
    `time` VARCHAR(20) NOT NULL COMMENT '发布日期',
    `description` LONGTEXT NOT NULL COMMENT '职位描述'
)ENGINE=INNODB CHARSET=UTF8;